{
  "openapi": "3.0.0",
  "info": {
    "title": "Atlas",
    "description": "Essa é uma documentação sobre a Atlas API",
    "version": "1.0.0",
    "contact": {
      "email": "victorxrp@gmail.com"
    }
  },
  "paths": {
    "/users": {
      "post": {
        "tags": [
          "Users"
        ],
        "summary": "Cria um novo usuário",
        "description": "Cria um novo usuário",
        "requestBody": {
          "description": "Campos obrigatórios para criação de um usuário.",
          "required": true,
          "content": {
            "application.json": {
              "schema": {
                "type": "object",
                "properties": {
                  "name": {
                    "type": "string"
                  },
                  "email": {
                    "type": "string"
                  }
                },
                "example": {
                  "name": "user name",
                  "email": "email@email.com"
                }
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Operação realizada com sucesso",
            "content": {
              "application.json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "id": {
                      "type": "string"
                    },
                    "admin": {
                      "type": "boolean"
                    },
                    "name": {
                      "type": "string"
                    },
                    "email": {
                      "type": "string"
                    },
                    "created_at": {
                      "type": "string"
                    },
                    "updated_at": {
                      "type": "string"
                    }
                  },
                  "example": {
                    "id": "6b4a22fd-1efb-4faf-b60d-32f052086da3",
                    "admin": false,
                    "name": "John Doe",
                    "email": "johndoe@email.com",
                    "created_at": "2021-03-19T00:26:55.410Z",
                    "updated_at": "2021-03-19T00:26:55.410Z"
                  }
                }
              }
            }
          },
          "400": {
            "description": "Já existe um usuário com o e-mail informado",
            "content": {
              "application.json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "error": {
                      "type": "string"
                    }
                  },
                  "example": {
                    "error": "Email already is in use"
                  }
                }
              }
            }
          }
        }
      },
      "get": {
        "tags": [
          "Users"
        ],
        "summary": "Retorna todos os usuários",
        "description": "Consulta somente realizada por usuários `Admin`",
        "parameters": [
          {
            "name": "user_id",
            "in": "header",
            "required": true,
            "type": "string",
            "format": "uuid"
          }
        ],
        "responses": {
          "200": {
            "description": "Operação realizada com sucesso!",
            "content": {
              "applicaton/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "type": "object",
                    "properties": {
                      "id": {
                        "type": "string"
                      },
                      "admin": {
                        "type": "boolean"
                      },
                      "name": {
                        "type": "boolean"
                      },
                      "email": {
                        "type": "string"
                      },
                      "created_at": {
                        "type": "string"
                      },
                      "updated_at": {
                        "type": "string"
                      }
                    }
                  }
                },
                "example": [
                  {
                    "id": "6b4a22fd-1efb-4faf-b60d-32f052086da3",
                    "name": "John Doe",
                    "admin": true,
                    "email": "johndoe@email.com",
                    "created_at": "2021-03-19T00:26:55.410Z",
                    "updated_at": "2021-03-19T00:26:55.410Z"
                  },

                  {
                    "id": "6b4a22fd-1efb-4faf-b60d-32f052086da3",
                    "name": "John Doe",
                    "admin": false,
                    "email": "johndoe@email.com",
                    "created_at": "2021-03-19T00:26:55.410Z",
                    "updated_at": "2021-03-19T00:26:55.410Z"
                  }
                ]
              }
            }
          },
          "400": {
            "description": "Você precisa ser um usuário admin para realizar essa requisição.",
            "content": {
              "application.json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "error": {
                      "type": "string"
                    }
                  },
                  "example": {
                    "error": "You need to be an administrator to list all users"
                  }
                }
              }
            }
          }
        }
      } 
    },
    "/users/{user_id}": {
      "get": {
        "tags": [
          "Users"
        ],
        "summary": "Retorna um usuário específico",
        "description": "Consulta somente realizada por usuários `Admin`",
        "parameters": [
          {
            "name": "user_id",
            "in": "path",
            "required": true,
            "type": "string",
            "format": "uuid"
          }
        ],
        "responses": {
          "200": {
            "description": "Operação realizada com sucesso!",
            "content": {
              "applicaton/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "type": "object",
                    "properties": {
                      "id": {
                        "type": "string"
                      },
                      "admin": {
                        "type": "boolean"
                      },
                      "name": {
                        "type": "boolean"
                      },
                      "email": {
                        "type": "string"
                      },
                      "created_at": {
                        "type": "string"
                      },
                      "updated_at": {
                        "type": "string"
                      }
                    }
                  }
                },
                "example": [
                  {
                    "id": "6b4a22fd-1efb-4faf-b60d-32f052086da3",
                    "name": "John Doe",
                    "admin": false,
                    "email": "johndoe@email.com",
                    "created_at": "2021-03-19T00:26:55.410Z",
                    "updated_at": "2021-03-19T00:26:55.410Z"
                  }
                ]
              }
            }
          },
          "404": {
            "description": "Usuário não encontrado.",
            "content": {
              "application.json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "error": {
                      "type": "string"
                    }
                  },
                  "example": {
                    "error": "User not found"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/users/{user_id}/admin": {
      "patch": {
        "tags": [
          "Users"
        ],
        "summary": "Torna um usuário Admin",
        "description": "Torna um usuário `Admin`",
        "parameters": [
          {
            "name": "user_id",
            "type": "string",
            "format": "uuid",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Operação realizada com sucesso!",
            "content": {
              "applicaton/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "type": "object",
                    "properties": {
                      "id": {
                        "type": "string"
                      },
                      "admin": {
                        "type": "boolean"
                      },
                      "name": {
                        "type": "boolean"
                      },
                      "email": {
                        "type": "string"
                      },
                      "created_at": {
                        "type": "string"
                      },
                      "updated_at": {
                        "type": "string"
                      }
                    }
                  }
                },
                "example": [
                  {
                    "id": "6b4a22fd-1efb-4faf-b60d-32f052086da3",
                    "name": "John Doe",
                    "admin": true,
                    "email": "johndoe@email.com",
                    "created_at": "2021-03-19T00:26:55.410Z",
                    "updated_at": "2021-03-19T00:26:55.410Z"
                  }
                ]
              }
            }
          },
          "404": {
            "description": "Usuário não encontrado.",
            "content": {
              "application.json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "error": {
                      "type": "string"
                    }
                  },
                  "example": {
                    "error": "User not found"
                  }
                }
              }
            }
          }
        }
      }
    }
  },
  "components":{
    "schemas": {
      "User": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string",
            "format": "uuid"
          },
          "name": {
            "type": "string"
          },
          "admin": {
            "type": "boolean"
          },
          "email": {
            "type": "string"
          },
          "created_at": {
            "type": "date"
          },
          "updated_at": {
            "type": "date"
          }
        }
      }
    }
  }
}